Doc improvement 6
supertokens/docs pull request #133
Opened 2021-09-28 14:34 UTC by jscyo

## Summary of change
(A few sentences about this PR)

## Related issues
#110 

## Remaining TODOs for this PR
none

2021-09-29 12:58 UTC, jscyo commented
Feedback:
- In the get user info page add sections for backend and frontend, in the frontend section link to the session subsection which talks about getting user info on the frontend.
- in getUserByEmail, it returns an array, fix variable name
- link to the wiki pages to get more info on the user object
- Add get user info code snippets for golang
- change the comment to "This is a core hosted for demo purposes. You can use this, but makes sure to change it to your core instance URI eventually."
- remove the disable fetch interceptors guide

2021-09-30 15:54 UTC, rishabhpoddar commented
Please read your work. In the get user info docs, it says "You can a user's information"

2021-09-30 16:03 UTC, rishabhpoddar requested changes

2021-09-30 16:03 UTC, rishabhpoddar commented on v2/thirdpartyemailpassword/advanced-customizations/react-component-override/usage.mdx
> +            EmailPasswordSignInHeader: ({ DefaultComponent, ...props }) => {
Did you change the list of this on the auth-react docs too?

2021-10-01 06:41 UTC, merged