recommend SuperTokensWrapper and update for session context loading
supertokens/docs pull request #370
Opened 2022-07-03 22:28 UTC by porcellus

## Summary of change

- Recommend `SessionAuthWrapper`
- Update to have `loading` in SessionContext

## Related issues
- https://github.com/supertokens/supertokens-auth-react/pull/493

## Checklist
- [ ] Algolia search needs to be updated? (If there is a new sub docs project, then yes)
- [ ] Sitemap needs to be updated? (If there is a new sub docs project, then yes)
- [x] Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)
- [ ] Changes required to the demo apps corresponding to the docs?

2022-07-04 08:19 UTC, rishabhpoddar requested changes

2022-07-04 08:19 UTC, rishabhpoddar commented on v2/emailpassword/quick-setup/frontend.mdx
> +:::
You can make this as a bullet point in the previous notice tooltip.

2022-07-04 08:19 UTC, rishabhpoddar commented on v2/emailpassword/quick-setup/frontend.mdx
> +        </SuperTokensWrapper>);
```suggestion
       return (
       <SuperTokensWrapper>
            {/*Your app components*/}
        </SuperTokensWrapper>);
```

2022-07-04 08:19 UTC, rishabhpoddar commented on v2/session/common-customizations/sessions/checking-session-front-end.mdx
> +            // This will never occur if you set requireAuth to true in the SessionAuth component
```suggestion
            // Session loading is generally very fast, so we do not recommend you to use a loading screen here.
```

2022-07-04 08:19 UTC, rishabhpoddar commented on v2/session/quick-setup/frontend.mdx
> +       </SuperTokensWrapper>);
```suggestion
       return (
       <SuperTokensWrapper>
         {/*Your app components*/}
       </SuperTokensWrapper>);
```

2022-07-04 11:13 UTC, porcellus commented on v2/emailpassword/supabase-intergration/frontend-changes.mdx
> +  }, [session.loading, !session.loading && session.accessTokenPayload])
We can, I just figured it could cause unnecessary re-renders, but it shouldn't be an issue.

2022-07-05 08:03 UTC, rishabhpoddar requested changes

2022-07-05 08:03 UTC, rishabhpoddar commented on v2/emailpassword/quick-setup/frontend.mdx
> +- We've wrapped the entire application with `SuperTokensWrapper`. This is optional but provides session information in all of your components. Check [here](../common-customizations/get-user-info#on-t
```suggestion
- We've wrapped the entire application with `SuperTokensWrapper`. This provides session information in all of your components. Check [here](../common-customizations/get-user-info#on-the-frontend) to see how you can access it.
```

2022-07-05 08:03 UTC, rishabhpoddar commented on v2/emailpassword/common-customizations/sessions/with-jwt/read-claims.mdx
>      let role = accessTokenPayload.role;
(Needs to be made here and all the places where this is there)

2022-07-05 12:51 UTC, rishabhpoddar approved these changes

2022-07-06 09:13 UTC, merged