Doc: Set specific SMTP username
supertokens/docs pull request #444
Opened 2022-08-27 09:26 UTC by utsavdotpro

## Summary of change
Feature PR: 

## Related issues
- https://github.com/supertokens/supertokens-node/issues/375

## Checklist
- [ ] Algolia search needs to be updated? (If there is a new sub docs project, then yes)
- [ ] Sitemap needs to be updated? (If there is a new sub docs project, then yes)
- [ ] Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)
- [ ] Changes required to the demo apps corresponding to the docs?

## Remaining TODOs for this PR
NA

2022-08-28 06:58 UTC, rishabhpoddar requested changes

2022-08-28 06:58 UTC, rishabhpoddar commented on v2/emailpassword/email-delivery/smtp/configure-smtp.mdx
> +                        username="...", # this is optional. In case not given, from.email will be used instead
this is for the python SDK, which doesn't have this setting yet. Can you please remove this?

2022-08-30 13:36 UTC, merged

2022-08-30 13:36 UTC, rishabhpoddar commented
Thanks @utsavdotpro we will take it from here :)

2022-08-30 13:37 UTC, rishabhpoddar commented
I have also added your GH profile on the supertokens-core readme! :)

2022-08-30 14:13 UTC, utsavdotpro commented
Thanks @rishabhpoddar.
I was on a short vacation so couldn't reply earlier. I am available now and happy to contribute further if you need it 😄

2022-08-30 14:14 UTC, rishabhpoddar commented
Really appreciate your help so far :) 

You could contribute more by:
- Adding a unit test for this change. 
- Making a similar change to our python / golang repos.