Eliminate duplicate init call
supertokens/docs pull request #579
Opened 2023-01-19 15:15 UTC by alisher-aituarov

## Summary of change
Update non-react app examples to use `supertokens-auth-react` on the main route instead of `supertokens-web-js`

## Related issues
- https://github.com/supertokens/supertokens-auth-react/issues/616

## Checklist
- [ ] Algolia search needs to be updated? (If there is a new sub docs project, then yes)
- [ ] Sitemap needs to be updated? (If there is a new sub docs project, then yes)
- [ ] Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)
- [ ] Changes required to the demo apps corresponding to the docs?

## Remaining TODOs for this PR

2023-01-20 02:44 UTC, porcellus requested changes

2023-01-20 14:02 UTC, porcellus requested changes
We also need to change sections like: https://deploy-preview-579--admiring-bhabha-7b1be9.netlify.app/docs/thirdpartyemailpassword/common-customizations/sessions/multiple-api-endpoints#step-2-frontend-config

2023-01-20 20:33 UTC, porcellus requested changes
- There are a few places that still need to be updated (e.g: https://deploy-preview-579--admiring-bhabha-7b1be9.netlify.app/docs/thirdpartyemailpassword/common-customizations/changing-base-path/website-base-path), but in general searching for `supertokensAuthComponent` and "reflected in both" should be useful.
- There are conflicts with the base branch

2023-01-23 05:22 UTC, alisher-aituarov commented
Typechecking is failing because of styles

2023-01-25 21:19 UTC, porcellus requested changes
- There are a few places where we still refer to the split configs, search for "reflected in both"
- When the only content inside a tab is a code block with a title (I noticed this for "main.ts" or "/app/app.component.ts" snippets). It looks a bit strange. I think we can remove these titles.
- See if you could replace `<Answer title="Prebuilt UI">` with `PreBuiltOrCustomUISwitcher` + `CustomUIContent`/`PreBuiltUIContent`

2023-01-25 21:19 UTC, porcellus commented on v2/src/theme/DocItem/index.js
> -          Which frontend SDK do you use?
Why did these change?

2023-04-11 20:51 UTC, porcellus requested changes

2023-04-11 20:51 UTC, porcellus commented on v2/emailpassword/common-customizations/sessions/share-session-across-sub-domains.mdx
> +
Why was this added?

2023-04-13 23:01 UTC, porcellus approved these changes

2023-04-17 06:33 UTC, rishabhpoddar requested changes

2023-04-17 06:33 UTC, rishabhpoddar commented on v2/emailpassword/pre-built-ui/setup/frontend.mdx
> +- After initializing `supertokens-auth-react`, we can use either the `supertokens-auth-react` or `supertokens-web-js` in the application, since the former also initializes the latter.
Redo this part of the docs to make it very clear what supertokens-auth-react SDK is for, and that adding react won't increase the bundle size of your app other than the auth routes. Do NOT mention web-js

2023-04-17 06:33 UTC, rishabhpoddar commented on v2/emailpassword/pre-built-ui/setup/frontend.mdx
> +- After initializing `supertokens-auth-react`, we can use either the `supertokens-auth-react` or `supertokens-web-js` in the application, since the former also initializes the latter.
Same thing goes for the vue section

2023-04-17 06:33 UTC, rishabhpoddar commented on v2/emailpassword/pre-built-ui/setup/frontend.mdx
>  **Architecture**
there is a section about "Redirect user to the login page" in https://deploy-preview-579--admiring-bhabha-7b1be9.netlify.app/docs/emailpassword/pre-built-ui/auth-redirection. Why can't users use `redirectToAuth` for angular and vue as well?

2023-04-17 06:33 UTC, rishabhpoddar commented on v2/emailpassword/pre-built-ui/enable-email-verification.mdx
the code snippets for angular and vue are essentially identical here.. just remove the angular and vue tabs and the content will get automatically replicated from the reactjs tab. 

This applies to all other code snippets changes in the PR as well wherein the angular and vue is the same as react. Also, you don't need to have the `title="/app/app.component.ts "` stuff anymore for angular and vue cause there are no two inits.

2023-04-17 06:33 UTC, rishabhpoddar commented on v2/thirdparty/common-customizations/sessions/share-session-across-sub-domains.mdx
There are still code snippets for angular and vue wherein we use web-js for pre built UI. See here: https://deploy-preview-579--admiring-bhabha-7b1be9.netlify.app/docs/emailpassword/common-customizations/sessions/protecting-frontend-routes

2023-04-17 06:33 UTC, rishabhpoddar commented on v2/thirdparty/common-customizations/sessions/share-session-across-sub-domains.mdx
this page still has web-js and auth-react code snippets.. why?

2023-04-17 06:35 UTC, rishabhpoddar commented on v2/thirdparty/common-customizations/sessions/share-session-across-sub-domains.mdx
Make sure it's solved for all pages.. i randomly stumbled upon this one.

2023-04-27 06:06 UTC, rishabhpoddar requested changes

2023-04-27 06:06 UTC, rishabhpoddar commented on v2/emailpassword/common-customizations/email-verification/about.mdx
Instead of repeating the code snippet here, we can just use `~COPY-TABS=reactjs`? (same goes for vue js)

2023-04-27 06:06 UTC, rishabhpoddar commented on v2/emailpassword/common-customizations/email-verification/protecting-routes.mdx
> +
why can't we use copy tabs here and copy from angular (for vue js - instead of copying the code manually)?

2023-04-27 06:06 UTC, rishabhpoddar commented on v2/emailpassword/common-customizations/get-user-info.mdx
> +
this can use copy tabs and copy from the without react context sub tab of the react tab?

2023-05-01 10:30 UTC, rishabhpoddar approved these changes

2023-05-03 06:33 UTC, merged