add info about yarn and npmv6 installs
supertokens/docs pull request #590
Opened 2023-02-06 08:38 UTC by porcellus

## Summary of change
add info about yarn and npmv6 installs

## Related issues
- Problems about missing deps on discord

## Checklist
- [ ] Algolia search needs to be updated? (If there is a new sub docs project, then yes)
- [ ] Sitemap needs to be updated? (If there is a new sub docs project, then yes)
- [x] Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)
- [ ] Changes required to the demo apps corresponding to the docs?

2023-02-06 09:48 UTC, rishabhpoddar requested changes

2023-02-06 09:48 UTC, rishabhpoddar commented on v2/emailpassword/pre-built-ui/setup/frontend.mdx
have sub tabs instead like npm > 6 (will be default selected), npm <= 6, yarn

2023-02-12 01:29 UTC, porcellus commented
![image](https://user-images.githubusercontent.com/1129990/218288226-4119d2b2-3e5d-4567-b71e-c9626e557c7a.png)

2023-02-12 05:09 UTC, rishabhpoddar requested changes

2023-02-12 05:09 UTC, rishabhpoddar commented on v2/emailpassword/pre-built-ui/setup/frontend.mdx
>  import AppInfoForm from "/src/components/appInfoForm"
these changes are good. However, there are a few other instances of yarn / npm being used with supertokens-auth-react - for examlpe in here: https://deploy-preview-590--admiring-bhabha-7b1be9.netlify.app/docs/emailpassword/nextjs/init.

Please make sure to cover all such cases.

2023-02-12 13:46 UTC, rishabhpoddar approved these changes

2023-02-12 13:46 UTC, merged