Added a self hosting option for AWS
supertokens/docs pull request #803
Opened 2024-06-10 23:53 UTC by AlaShibanAtKlo

## Summary of change
We're fans of Supertokens and added support to install it on AWS using stacksnap 

## Related issues
- N/A

## Checklist
- [X] Algolia search needs to be updated? (If there is a new sub docs project, then yes)
- [X] Sitemap needs to be updated? (If there is a new sub docs project, then yes)
- [X] Checked for broken links? (Run `cd v2 && MODE=production npx docusaurus build`)
- [ ] Changes required to the demo apps corresponding to the docs?

2024-06-11 05:09 UTC, rishabhpoddar requested changes

2024-06-11 05:09 UTC, rishabhpoddar commented on v2/passwordless/pre-built-ui/setup/core/self-hosted-with-aws.mdx
> +---
Please modify the [sidebar.json](https://github.com/supertokens/docs/blob/a4e2261fb53b295834f55239747e4a40835d18c6/v2/passwordless/sidebars.js) to add this page

2024-06-11 05:09 UTC, rishabhpoddar commented on v2/passwordless/pre-built-ui/setup/core/self-hosted-with-aws.mdx
> +
please replicate this across the following recipes:
- emailpassword
- thirdparty
- thirdparty + emailpassword
- thirdparty + passwordless
- session

2024-06-11 05:09 UTC, rishabhpoddar commented on v2/passwordless/pre-built-ui/setup/core/self-hosted-with-aws.mdx
> +---
neds to be replicated in the custom ui section of the recipe as well please.

2024-06-11 05:09 UTC, rishabhpoddar commented
Hey @AlaShibanAtKlo ! This is seriously cool! Thank you. I have added a few comments.

2024-06-11 18:02 UTC, AlaShibanAtKlo commented
> Hey @AlaShibanAtKlo ! This is seriously cool! Thank you. I have added a few comments.

I made the changes, I believe i caught all the placements 🤞thanks @rishabhpoddar !

2024-06-11 22:31 UTC, AlaShibanAtKlo commented
@rishabhpoddar ok I fixed everything and I think everything is passing now 🤞

2024-06-12 06:18 UTC, merged

2024-06-12 06:19 UTC, rishabhpoddar commented
Thanks @AlaShibanAtKlo ! Please feel free to add yourself to the [supertokens-core readme](https://github.com/supertokens/supertokens-core) :)